required-players: 2
countdown-seconds: 30
lobby-spawn:
  world: 'world'
  x: 8.5
  y: -60
  z: 8.5
  yaw: 0
  pitch: 0
arenas:
  0:
    world: 'world'
      x: 12.5
      y: -60
      z: 15.5
      yaw: 150
      pitch: 11
  1:
    world: 'world'
      x: 4.5
      y: -60
      z: 15.5
      yaw: -150
      pitch: 11