required-players: 1
countdown-seconds: 10
cat-lives: 9
lobby-spawn:
  world: 'world'
  x: 8.5
  y: -60
  z: 8.5
  yaw: 0
  pitch: 0
arenas:
  0:
    name: 'SandCastle'
    lobby:
      world: 'SandCastle'
      x: 0.5
      y: 125
      z: 0.5
      yaw: 0
      pitch: 0
    red:
      x: 3
      y: 126
      z: 0.5
      yaw: 150
      pitch: 11
    blue:
      x: 0.5
      y: 126
      z: 3.5
      yaw: 150
      pitch: 11
    green:
      x: -2.5
      y: 126
      z: 0.5
      yaw: 150
      pitch: 11
    pink:
      x: 0.5
      y: 126
      z: -2.5
      yaw: 150
      pitch: 11
    pos1:
      x: 0.5
      y: 126
      z: -2.5
    pos2:
      x: 0.5
      y: 126
      z: -2.5
  1:
    name: 'Glacier'
    lobby:
      world: 'world'
      x: 4.5
      y: -60
      z: 15.5
      yaw: -150
      pitch: 11
    red:
      x: 12.5
      y: -60
      z: 15.5
      yaw: 150
      pitch: 11
    blue:
      x: 12.5
      y: -60
      z: 15.5
      yaw: 150
      pitch: 11
    green:
      x: 12.5
      y: -60
      z: 15.5
      yaw: 150
      pitch: 11
    pink:
      x: 12.5
      y: -60
      z: 15.5
      yaw: 150
      pitch: 11
    pos1:
      x: 0.5
      y: 126
      z: -2.5
      yaw: 150
      pitch: 11
    pos2:
      x: 0.5
      y: 126
      z: -2.5
      yaw: 150
      pitch: 11