required-players: 1
countdown-seconds: 10
cat-lives: 9
lobby-spawn:
  world: 'world'
  x: 8.5
  y: -60
  z: 8.5
  yaw: 0
  pitch: 0
arenas:
  0:
    name: 'sandcastle'
    sign:
      world: 'world'
      x: 0.5
      y: 125
      z: 0.5
    lobby:
      world: 'sandcastle'
      x: 0.5
      y: 125
      z: 0.5
      yaw: 0
      pitch: 0
    red:
      team-spawn:
        x: 3
        y: 126
        z: 0.5
        yaw: 150
        pitch: 11
      villager-spawn:
        x: 3
        y: 126
        z: 0.5
        yaw: 150
        pitch: 11
      dropper:
        x: 3
        y: 126
        z: 0.5
      pos1:
        x: 3
        y: 126
        z: 0.5
      pos2:
        x: 3
        y: 126
        z: 0.5
    blue:
      team-spawn:
        x: 3
        y: 126
        z: 0.5
        yaw: 150
        pitch: 11
      villager-spawn:
        x: 3
        y: 126
        z: 0.5
        yaw: 150
        pitch: 11
      dropper:
        x: 3
        y: 126
        z: 0.5
      pos1:
        x: 3
        y: 126
        z: 0.5
      pos2:
        x: 3
        y: 126
        z: 0.5
    green:
      team-spawn:
        x: 3
        y: 126
        z: 0.5
        yaw: 150
        pitch: 11
      villager-spawn:
        x: 3
        y: 126
        z: 0.5
        yaw: 150
        pitch: 11
      dropper:
        x: 3
        y: 126
        z: 0.5
      pos1:
        x: 3
        y: 126
        z: 0.5
      pos2:
        x: 3
        y: 126
        z: 0.5
    pink:
      team-spawn:
        x: 3
        y: 126
        z: 0.5
        yaw: 150
        pitch: 11
      villager-spawn:
        x: 3
        y: 126
        z: 0.5
        yaw: 150
        pitch: 11
      dropper:
        x: 3
        y: 126
        z: 0.5
      pos1:
        x: 3
        y: 126
        z: 0.5
      pos2:
        x: 3
        y: 126
        z: 0.5
    pos1:
      x: 0.5
      y: 126
      z: -2.5
    pos2:
      x: 0.5
      y: 126
      z: -2.5
    droppers:
      0:
        x: 0.5
        y: 126
        z: -2.5
      1:
        x: 0.5
        y: 126
        z: -2.5

  1:
    name: 'Glacier'
    sign:
      world: 'world'
      x: 0.5
      y: 125
      z: 0.5
    lobby:
      world: 'Glacier'
      x: 4.5
      y: -60
      z: 15.5
      yaw: -150
      pitch: 11
    red:
      team-spawn:
        x: 3
        y: 126
        z: 0.5
        yaw: 150
        pitch: 11
      villager-spawn:
        x: 3
        y: 126
        z: 0.5
        yaw: 150
        pitch: 11
      dropper:
        x: 3
        y: 126
        z: 0.5
      pos1:
        x: 3
        y: 126
        z: 0.5
      pos2:
        x: 3
        y: 126
        z: 0.5
    blue:
      team-spawn:
        x: 3
        y: 126
        z: 0.5
        yaw: 150
        pitch: 11
      villager-spawn:
        x: 3
        y: 126
        z: 0.5
        yaw: 150
        pitch: 11
      dropper:
        x: 3
        y: 126
        z: 0.5
      pos1:
        x: 3
        y: 126
        z: 0.5
      pos2:
        x: 3
        y: 126
        z: 0.5
    green:
      team-spawn:
        x: 3
        y: 126
        z: 0.5
        yaw: 150
        pitch: 11
      villager-spawn:
        x: 3
        y: 126
        z: 0.5
        yaw: 150
        pitch: 11
      dropper:
        x: 3
        y: 126
        z: 0.5
      pos1:
        x: 3
        y: 126
        z: 0.5
      pos2:
        x: 3
        y: 126
        z: 0.5
    pink:
      team-spawn:
        x: 3
        y: 126
        z: 0.5
        yaw: 150
        pitch: 11
      villager-spawn:
        x: 3
        y: 126
        z: 0.5
        yaw: 150
        pitch: 11
      dropper:
        x: 3
        y: 126
        z: 0.5
      pos1:
        x: 3
        y: 126
        z: 0.5
      pos2:
        x: 3
        y: 126
        z: 0.5
    pos1:
      x: 0.5
      y: 126
      z: -2.5
      yaw: 150
      pitch: 11
    pos2:
      x: 0.5
      y: 126
      z: -2.5
      yaw: 150
      pitch: 11